name: counter_bloc
description: A new Flutter project.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ">=3.0.6 <4.0.0" 

dependencies:
  flutter:
    sdk: flutter
  remote_province:
    path: ../../packages/remote_province
  bloc: ^8.1.2
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.3
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
