name: example
description: A new Flutter project.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ">=3.0.6 <4.0.0" 

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  remote_province:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
