name: counter_state_notifier
version: 1.0.0+1
homepage: https://github.com/chimon2000/remote_state
author: Ryan Edge <ryan.c.edge@outlook.com>
publish_to: 'none'

environment:
  sdk: ">=3.0.6 <4.0.0" 

dependencies:
  flutter:
    sdk: flutter
  remote_province:
    path: ../../packages/remote_province
  flutter_state_notifier: ^1.0.0
  provider: ^6.0.5
  state_notifier: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
