name: remote_province
version: 2.0.0
homepage: https://github.com/agmoss/remote_province
description: Tools for mapping data from remote sources in Dart, similar to
  Elm's RemoteData.
environment:
  sdk: ">=3.0.6 <4.0.0"
dependencies:
  freezed_annotation: ^2.4.1
  meta: ">=1.0.0 <3.0.0"
dev_dependencies:
  build_runner: ^2.4.6
  coverage: ^1.6.3
  freezed: ^2.4.3
  test: ^1.16.5
